version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - nats-streaming
    links:
      - postgres
      - redis
      - "nats-streaming:nats"

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    restart: always
    command: "-p 4222 -p 6222 -p 8222 -m 8224 --store file --dir /data/msg"
    volumes:
      - ./nats-server.conf:/data/nats-server.conf

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - config/redis.env
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - config/pg.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - NATS_ENGINE=1
      - NATS_CONNECT=nats:4222
    command: ["clickhouse-server", "--config-file=/etc/clickhouse-server/config.xml"]
    volumes:
      - ./clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

networks:
  clickhouse-network:
    driver: bridge

volumes:
  clickhouse-server:
  clickhouse_data:
  clickhouse_logs:
  postgres:
  redis:
    driver: local
